### ISSUE TITLE
Unable to craft certain items

### ISSUE THREAD

**Issue by UnnamedM** [pixeldreamstudios/FantasyMC#18]
### Describe the Bug

I'm not sure if it's just me but I haven't been able to craft items that aren't from vanilla minecraft. One of them being from the Alloy forgery and another one having to craft cobblestone with cobblestone splitter.

### Screenshots

![2023-05-02_19 10 52](https://user-images.githubusercontent.com/132409898/235804806-9defcd9c-84e4-44c0-ae16-2edf249451a1.png)
![2023-05-02_19 11 09](https://user-images.githubusercontent.com/132409898/235804811-5d7c967d-c9c7-476b-91d3-2e6532567737.png)
![2023-05-02_19 11 25](https://user-images.githubusercontent.com/132409898/235804815-4eb14296-3e8e-4724-941d-622d071b219d.png)

### Modpack Version

Current version of Fantasy Minecraft is v11.3

**Comment by kyber-6** [comment]
Strange, can you not craft anything at all that is not Vanilla? If that's the case then re-install the modpack/repair your installation.
