### ISSUE TITLE
unable to join the nether-dimension

### ISSUE THREAD

**Issue by siqNezz1337** [pixeldreamstudios/FantasyMC#21]
Greetings,

I'm currently playing the v11.3 of the modpack on a private Server with Friends via g-portal. The Playtrough seem fine unless I/we try to enter the Nether. The Nether won't generate inside of the max tick-range (60 sek.) and restarts.

What I've tried so far:
- deleting level.dat and level.dat_old
- reinstalling the modpack
- increasing the max tick-range to 120 sek.
- joining the nether in survival mode via Portal (not getting the advancements "We Need To Go Deeper" or "Incendium")
- joining the nether in creative mode via command (execute in minecraft:the_nether run tp siqNezz1337 170 80 170 and getting advancements "We Need To Go Deeper" or "Incendium")

console-output
[server-shutdown-2023-05-08_06.50.54.txt](https://github.com/pixeldreamstudios/FantasyMinecraft/files/11417863/server-shutdown-2023-05-08_06.50.54.txt)

kubejs log file
[logs_kubejs_server.txt](https://github.com/pixeldreamstudios/FantasyMinecraft/files/11417864/logs_kubejs_server.txt)

Any Suggestions? If you need any other kind of Document, let me know. Thanks in advance!

**Comment by siqNezz1337** [comment]
[crash-2023-05-08_07.05.24-server.txt](https://github.com/pixeldreamstudios/FantasyMinecraft/files/11417906/crash-2023-05-08_07.05.24-server.txt)

**Comment by kyber-6** [comment]
Try reducing the server's render distance or pre-generating the nether with Chunky.
