### ISSUE TITLE
Unable to join private server

### ISSUE THREAD

**Issue by SaintLamp** [pixeldreamstudios/FantasyMC#22]
### Describe the Bug

me and one other player are unable to join my private server, for me currently it hangs on "loading terrain..." and never actually joins the server.

steps I have tried

1. restarting server
2. restarting client
3. removing iris because I heard it may cause problems 
4. completely stopping server and then starting it again

### Crash-logs

https://pastebin.com/GRNyKBP5 a log of what happens when I try to join the server

### Modpack Version

 FantasyMC 1.19.2-v11.5, both server and clients

**Comment by kyber-6** [comment]
You can try removing the No Chat Reports mod.
