### ISSUE TITLE
Can't interact with villagers

### ISSUE THREAD

**Issue by TitoHacks** [pixeldreamstudios/FantasyMC#24]
### Describe the Bug

I don't know what happened. I was playing on my world and tried to interact with a villager, but no trading GUI showed up. I tried with another villager, but nothing. If I have some emeralds on hand, the villager shows an item in his hands, but no trading GUI shows. I can trade with the wandering trader but not with villagers.

### Screenshots

https://github.com/pixeldreamstudios/FantasyMinecraft/assets/35603092/6e9b2017-895b-4dc1-b54d-a8a1fdb015ca

### Modpack Version

v12.2

**Comment by KevzCz** [comment]
I'll disable the powers that make you unable to trade with villagers in the next update
