### ISSUE TITLE
LevelZ quests sometimes fails to trigger

### ISSUE THREAD

**Issue by HydroH** [pixeldreamstudios/FantasyMC#26]
### Describe the bug

The "All the rounds" and "Player Level" quests in the LevelZ quests can fail to trigger if player aquires skill points very quickly and skip the required conditions.

### Reproduction Steps

Add skill points very quickly past 1, and the "All the rounds" quest fails to trigger.
Gain large amounts of xp at skill level 99 so it skips over 100, and the "Player level" quest fails to trigger.

### Mod pack version

v12.6

**Comment by KevzCz** [comment]
I'm unsure what "All the rounds" quest is but I'm guessing you're talking about the "All Rounder" quest, It's meant to be like that, a hidden quest.
As for the level 100 quest I can maybe fix that.

**Comment by HydroH** [comment]
Sorry, the "All Rounder" quest, is what I meant.
As for the "All Rounder" quest that requests all main stats over 20, if you have 19 20 20 20 20 and somehow you upgrade 2 points at the same time (maybe by completing other quests) then you get to 21 20 20 20 20 and the quest is not completed.

**Comment by KevzCz** [comment]
That quest had to be specific because of the limitations of ftbquests. The quest requirement doesn't tick that fast so there isnt much i can do. You could go into editing mode by click a wrench in the bottom right and complete it if you're stuck at that point.
