### ISSUE TITLE
Game crashes when interacting with backpacks

### ISSUE THREAD

**Issue by LeuckChris** [pixeldreamstudios/FantasyMC#27]
### Describe the bug

Whenever I shift-click a backpack to move it in my inventory or to a chest, my game crashes and I am getting  "stackoverfloweror: rendering item" as error message. 

### Reproduction Steps

Shift-click any backpack in your inventory. 

### Mod pack version

V.12.6

**Comment by kyber-6** [comment]
This will be fixed in the next update.
